name: Terraform DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-aws-infra:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning using GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Check Terraform version
        run: terraform version
        
      - name: Run Terraform init
        run: terraform init    

      - name: Run Terraform Format
        run: terraform fmt

      - name: Run Terraform Validate
        run: terraform validate        

      - name: Run Terraform Plan
        run: terraform plan

      #- name: Run Terraform Apply
      #  run: terraform apply -auto-approve 
